<?php
$parts =
array (
    'English-Les',
    'English-Eval',
    'Databases-Lec',
    'Databases-Tut',
    'Databases-Lab',
    'Databases-LabEval',
    'Web-Development-Lec',
    'Web-Development-Lab',
    'Web-Development-LabEval',
    'Computer-Generated-Images-Lec',
    'Computer-Generated-Images-Lab',
    'Python-Les',
    'Python-Lab',
    'Intelligent-Algorithms-Lec',
    'Intelligent-Algorithms-Tut',
    'Intelligent-Algorithms-Lab',
    'Qt-Lec',
    'Qt-Lab',
    'Functional-programming-Lec',
    'Functional-programming-Tut',
    'Functional-programming-Lab',
    'Logic-programming-Lec',
    'Logic-programming-Tut',
    'Logic-programming-Lab'
);
?>